//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCheckViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VCheckViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Configuration_Label_Button_Update {
            get {
                return ResourceManager.GetString("Configuration_Label_Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMS / LIS / HIS IP Address.
        /// </summary>
        public static string Configuration_Label_PMS_LIS_HIS {
            get {
                return ResourceManager.GetString("Configuration_Label_PMS_LIS_HIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMS / LIS / HIS Port Number.
        /// </summary>
        public static string Configuration_Label_PMS_LIS_HIS_PortNo {
            get {
                return ResourceManager.GetString("Configuration_Label_PMS_LIS_HIS_PortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Dashboard_Label_Loading {
            get {
                return ResourceManager.GetString("Dashboard_Label_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative.
        /// </summary>
        public static string Dashboard_Label_Negative {
            get {
                return ResourceManager.GetString("Dashboard_Label_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive.
        /// </summary>
        public static string Dashboard_Label_Positive {
            get {
                return ResourceManager.GetString("Dashboard_Label_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure optimal performance by regularly updating your analyzer software and firmware.&lt;nextline&gt;Get the latest versions of your analyzer..
        /// </summary>
        public static string Dashboard_Message_DownloadLatest {
            get {
                return ResourceManager.GetString("Dashboard_Message_DownloadLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard_Title_PageTitle {
            get {
                return ResourceManager.GetString("Dashboard_Title_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Devices.
        /// </summary>
        public static string Device_Label_AddedDevices {
            get {
                return ResourceManager.GetString("Device_Label_AddedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Device_Label_Button_Add {
            get {
                return ResourceManager.GetString("Device_Label_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Device.
        /// </summary>
        public static string Device_Label_Button_BackDevice {
            get {
                return ResourceManager.GetString("Device_Label_Button_BackDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to View Device.
        /// </summary>
        public static string Device_Label_Button_BackViewDevice {
            get {
                return ResourceManager.GetString("Device_Label_Button_BackViewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Device_Label_Button_Cancel {
            get {
                return ResourceManager.GetString("Device_Label_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Device_Label_Button_Delete {
            get {
                return ResourceManager.GetString("Device_Label_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Device_Label_Button_Edit {
            get {
                return ResourceManager.GetString("Device_Label_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Device_Label_Button_Update {
            get {
                return ResourceManager.GetString("Device_Label_Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device IP Address.
        /// </summary>
        public static string Device_Label_DeviceIPAddress {
            get {
                return ResourceManager.GetString("Device_Label_DeviceIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        public static string Device_Label_DeviceName {
            get {
                return ResourceManager.GetString("Device_Label_DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string General_Label_Busy {
            get {
                return ResourceManager.GetString("General_Label_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string General_Label_Create {
            get {
                return ResourceManager.GetString("General_Label_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string General_Label_Delete {
            get {
                return ResourceManager.GetString("General_Label_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string General_Label_Download {
            get {
                return ResourceManager.GetString("General_Label_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string General_Label_Edit {
            get {
                return ResourceManager.GetString("General_Label_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string General_Label_Next {
            get {
                return ResourceManager.GetString("General_Label_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string General_Label_No {
            get {
                return ResourceManager.GetString("General_Label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string General_Label_Number {
            get {
                return ResourceManager.GetString("General_Label_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string General_Label_OK {
            get {
                return ResourceManager.GetString("General_Label_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string General_Label_Prev {
            get {
                return ResourceManager.GetString("General_Label_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string General_Label_Previous {
            get {
                return ResourceManager.GetString("General_Label_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string General_Label_Ready {
            get {
                return ResourceManager.GetString("General_Label_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string General_Label_Save {
            get {
                return ResourceManager.GetString("General_Label_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string General_Label_Searchbar {
            get {
                return ResourceManager.GetString("General_Label_Searchbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select duration.
        /// </summary>
        public static string General_Label_SelectDuration {
            get {
                return ResourceManager.GetString("General_Label_SelectDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string General_Label_Send {
            get {
                return ResourceManager.GetString("General_Label_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string General_Label_Update {
            get {
                return ResourceManager.GetString("General_Label_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string General_Label_View {
            get {
                return ResourceManager.GetString("General_Label_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string General_Label_Yes {
            get {
                return ResourceManager.GetString("General_Label_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process. Please contact administrator..
        /// </summary>
        public static string General_Message_Error {
            get {
                return ResourceManager.GetString("General_Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occur. Please contact administrator..
        /// </summary>
        public static string General_Message_ErrorOccured {
            get {
                return ResourceManager.GetString("General_Message_ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes detected..
        /// </summary>
        public static string General_Message_NoChanges {
            get {
                return ResourceManager.GetString("General_Message_NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No completed test available..
        /// </summary>
        public static string General_Message_NoCompletedTest {
            get {
                return ResourceManager.GetString("General_Message_NoCompletedTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string General_Message_NoData {
            get {
                return ResourceManager.GetString("General_Message_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device available..
        /// </summary>
        public static string General_Message_NoDevice {
            get {
                return ResourceManager.GetString("General_Message_NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notification available..
        /// </summary>
        public static string General_Message_NoNotification {
            get {
                return ResourceManager.GetString("General_Message_NoNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scheduled test available..
        /// </summary>
        public static string General_Message_NoScheduleTest {
            get {
                return ResourceManager.GetString("General_Message_NoScheduleTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account are deactivated. Please contact administrator..
        /// </summary>
        public static string Login_ErrorMessage_AccountDeactivated {
            get {
                return ResourceManager.GetString("Login_ErrorMessage_AccountDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account are locked. Please contact administrator..
        /// </summary>
        public static string Login_ErrorMessage_AccountLocked {
            get {
                return ResourceManager.GetString("Login_ErrorMessage_AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account are not confirmed yet. Please confirm the account through email..
        /// </summary>
        public static string Login_ErrorMessage_AccountNotConfirmed {
            get {
                return ResourceManager.GetString("Login_ErrorMessage_AccountNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one lowercase letter..
        /// </summary>
        public static string Login_ErrorMessage_NoLowerCase {
            get {
                return ResourceManager.GetString("Login_ErrorMessage_NoLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one number..
        /// </summary>
        public static string Login_ErrorMessage_NoNumberChar {
            get {
                return ResourceManager.GetString("Login_ErrorMessage_NoNumberChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one special character..
        /// </summary>
        public static string Login_ErrorMessage_NoSpecialChar {
            get {
                return ResourceManager.GetString("Login_ErrorMessage_NoSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one uppercase letter..
        /// </summary>
        public static string Login_ErrorMessage_NoUpperCase {
            get {
                return ResourceManager.GetString("Login_ErrorMessage_NoUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must contain at least 8 characters..
        /// </summary>
        public static string Login_ErrorMessage_PasswordLessEightChar {
            get {
                return ResourceManager.GetString("Login_ErrorMessage_PasswordLessEightChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email linked to the account, please verify it is the correct email and try again..
        /// </summary>
        public static string Login_ErrorMessage_WrongEmail {
            get {
                return ResourceManager.GetString("Login_ErrorMessage_WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong login ID..
        /// </summary>
        public static string Login_ErrorMessage_WrongLoginID {
            get {
                return ResourceManager.GetString("Login_ErrorMessage_WrongLoginID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find user according to Login ID, please verify it is the correct login ID and try again..
        /// </summary>
        public static string Login_ErrorMessage_WrongLoginIDRecovery {
            get {
                return ResourceManager.GetString("Login_ErrorMessage_WrongLoginIDRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password. You have &lt;attemptcount&gt; attempt[s] left before account are locked..
        /// </summary>
        public static string Login_ErrorMessage_WrongPassword {
            get {
                return ResourceManager.GetString("Login_ErrorMessage_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Login ID and Email Address do not match..
        /// </summary>
        public static string Login_ErrorMessage_WrongUsernameEmail {
            get {
                return ResourceManager.GetString("Login_ErrorMessage_WrongUsernameEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Login ID or Password..
        /// </summary>
        public static string Login_ErrorMessage_WrongUsernamePassword {
            get {
                return ResourceManager.GetString("Login_ErrorMessage_WrongUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        public static string Login_Label_BackButton {
            get {
                return ResourceManager.GetString("Login_Label_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string Login_Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Login_Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string Login_Label_ForgetPassword {
            get {
                return ResourceManager.GetString("Login_Label_ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get accurate&lt;nextline&gt;results swiftly..
        /// </summary>
        public static string Login_Label_LeftMain {
            get {
                return ResourceManager.GetString("Login_Label_LeftMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to access your account.
        /// </summary>
        public static string Login_Label_LeftSub {
            get {
                return ResourceManager.GetString("Login_Label_LeftSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Label_LoginButton {
            get {
                return ResourceManager.GetString("Login_Label_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Label_MainPassword {
            get {
                return ResourceManager.GetString("Login_Label_MainPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Login_Label_MainUsername {
            get {
                return ResourceManager.GetString("Login_Label_MainUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string Login_Label_NewPassword {
            get {
                return ResourceManager.GetString("Login_Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string Login_Label_OldPassword {
            get {
                return ResourceManager.GetString("Login_Label_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password&lt;nextline&gt;Recovery.
        /// </summary>
        public static string Login_Label_PasswordRecovery {
            get {
                return ResourceManager.GetString("Login_Label_PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Login_Label_RegisterButton {
            get {
                return ResourceManager.GetString("Login_Label_RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Login_Label_ResetPassword {
            get {
                return ResourceManager.GetString("Login_Label_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occur when creating password. Please contact administrator..
        /// </summary>
        public static string Login_Message_CreatePasswordError {
            get {
                return ResourceManager.GetString("Login_Message_CreatePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New and Confirm password are not match..
        /// </summary>
        public static string Login_Message_PasswordNewConfirmMismatch {
            get {
                return ResourceManager.GetString("Login_Message_PasswordNewConfirmMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address, and we will send you a link to reset your password..
        /// </summary>
        public static string Login_Message_PasswordRecovery {
            get {
                return ResourceManager.GetString("Login_Message_PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have atleast have one digit, one lowercase, one uppercase and consist of eight characters..
        /// </summary>
        public static string Login_Message_PasswordRequirement {
            get {
                return ResourceManager.GetString("Login_Message_PasswordRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully reset..
        /// </summary>
        public static string Login_Message_PasswordResetted {
            get {
                return ResourceManager.GetString("Login_Message_PasswordResetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occur when removing password. Please contact administrator..
        /// </summary>
        public static string Login_Message_RemovePasswordError {
            get {
                return ResourceManager.GetString("Login_Message_RemovePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong current password..
        /// </summary>
        public static string Login_Message_WrongCurrentPassword {
            get {
                return ResourceManager.GetString("Login_Message_WrongCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong new password..
        /// </summary>
        public static string Login_Message_WrongNewPassword {
            get {
                return ResourceManager.GetString("Login_Message_WrongNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Title_PageTitle {
            get {
                return ResourceManager.GetString("Login_Title_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Main_Label_Logout {
            get {
                return ResourceManager.GetString("Main_Label_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Main_Label_ResetPassword {
            get {
                return ResourceManager.GetString("Main_Label_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Main_Label_SideMenuCollapse {
            get {
                return ResourceManager.GetString("Main_Label_SideMenuCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Main_Label_SideMenuDashboard {
            get {
                return ResourceManager.GetString("Main_Label_SideMenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Main_Label_SideMenuNotification {
            get {
                return ResourceManager.GetString("Main_Label_SideMenuNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Main_Label_SideMenuResults {
            get {
                return ResourceManager.GetString("Main_Label_SideMenuResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Main_Label_SideMenuSchedule {
            get {
                return ResourceManager.GetString("Main_Label_SideMenuSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Main_Label_SideMenuSetting {
            get {
                return ResourceManager.GetString("Main_Label_SideMenuSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        public static string Main_Label_ViewProfile {
            get {
                return ResourceManager.GetString("Main_Label_ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Test Results.
        /// </summary>
        public static string Notification_Label_CompletedTest {
            get {
                return ResourceManager.GetString("Notification_Label_CompletedTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show :.
        /// </summary>
        public static string Notification_Label_Show {
            get {
                return ResourceManager.GetString("Notification_Label_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Notification_Label_ShowAll {
            get {
                return ResourceManager.GetString("Notification_Label_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Test.
        /// </summary>
        public static string Notification_Label_UpcomingTest {
            get {
                return ResourceManager.GetString("Notification_Label_UpcomingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Filter.
        /// </summary>
        public static string Notification_Label_UpdateFilter {
            get {
                return ResourceManager.GetString("Notification_Label_UpdateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Notification_Label_Updates {
            get {
                return ResourceManager.GetString("Notification_Label_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification_Title_PageTitle {
            get {
                return ResourceManager.GetString("Notification_Title_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to add this new analyzer.
        /// </summary>
        public static string Popup_Message_AddAnalyzer {
            get {
                return ResourceManager.GetString("Popup_Message_AddAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Result API Failed..
        /// </summary>
        public static string Popup_Message_APIUpdateFailed {
            get {
                return ResourceManager.GetString("Popup_Message_APIUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Result API Successfully..
        /// </summary>
        public static string Popup_Message_APIUpdateSuccess {
            get {
                return ResourceManager.GetString("Popup_Message_APIUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Took too long sending request to the analyzer..
        /// </summary>
        public static string Popup_Message_CanceledSendToAnalyzer {
            get {
                return ResourceManager.GetString("Popup_Message_CanceledSendToAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to cancel this schedule?.
        /// </summary>
        public static string Popup_Message_CancelSchedule {
            get {
                return ResourceManager.GetString("Popup_Message_CancelSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check password again..
        /// </summary>
        public static string Popup_Message_CheckPassword {
            get {
                return ResourceManager.GetString("Popup_Message_CheckPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check username again..
        /// </summary>
        public static string Popup_Message_CheckUsername {
            get {
                return ResourceManager.GetString("Popup_Message_CheckUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password does not match..
        /// </summary>
        public static string Popup_Message_ConfirmPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("Popup_Message_ConfirmPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create this user profile?.
        /// </summary>
        public static string Popup_Message_CreateUser {
            get {
                return ResourceManager.GetString("Popup_Message_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user profile?.
        /// </summary>
        public static string Popup_Message_DeleteUser {
            get {
                return ResourceManager.GetString("Popup_Message_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Unique ID..
        /// </summary>
        public static string Popup_Message_EnterUniqueID {
            get {
                return ResourceManager.GetString("Popup_Message_EnterUniqueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add device, please contact system admin..
        /// </summary>
        public static string Popup_Message_FailedAddDevice {
            get {
                return ResourceManager.GetString("Popup_Message_FailedAddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove device, please contact System Admin..
        /// </summary>
        public static string Popup_Message_FailedDeleteDevice {
            get {
                return ResourceManager.GetString("Popup_Message_FailedDeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download Test Results listing..
        /// </summary>
        public static string Popup_Message_FailedDownloadListing {
            get {
                return ResourceManager.GetString("Popup_Message_FailedDownloadListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Open Print..
        /// </summary>
        public static string Popup_Message_FailedOpenPrint {
            get {
                return ResourceManager.GetString("Popup_Message_FailedOpenPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download..
        /// </summary>
        public static string Popup_Message_FailedToDownload {
            get {
                return ResourceManager.GetString("Popup_Message_FailedToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to print..
        /// </summary>
        public static string Popup_Message_FailedToPrint {
            get {
                return ResourceManager.GetString("Popup_Message_FailedToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send request to the analyzer..
        /// </summary>
        public static string Popup_Message_FailedToSendToAnalyzer {
            get {
                return ResourceManager.GetString("Popup_Message_FailedToSendToAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update device, please contact System Admin..
        /// </summary>
        public static string Popup_Message_FailedUpdateDevice {
            get {
                return ResourceManager.GetString("Popup_Message_FailedUpdateDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update LIS info..
        /// </summary>
        public static string Popup_Message_FailedUpdateLISInfo {
            get {
                return ResourceManager.GetString("Popup_Message_FailedUpdateLISInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input password..
        /// </summary>
        public static string Popup_Message_InputPassword {
            get {
                return ResourceManager.GetString("Popup_Message_InputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input username..
        /// </summary>
        public static string Popup_Message_InputUsername {
            get {
                return ResourceManager.GetString("Popup_Message_InputUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address and port number are unavailable to assign. Please type another value..
        /// </summary>
        public static string Popup_Message_IpPortUnavailable {
            get {
                return ResourceManager.GetString("Popup_Message_IpPortUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save this setting?.
        /// </summary>
        public static string Popup_Message_LanguageCountryChange {
            get {
                return ResourceManager.GetString("Popup_Message_LanguageCountryChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        public static string Popup_Message_Logout {
            get {
                return ResourceManager.GetString("Popup_Message_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device found that can receive request..
        /// </summary>
        public static string Popup_Message_NoDeviceFound {
            get {
                return ResourceManager.GetString("Popup_Message_NoDeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have send you a temporary password to your email. You can use it to log in. &lt;next line&gt; Once you are logged in, you can change it to your preferred password in .
        /// </summary>
        public static string Popup_Message_PasswordRecoveredP1 {
            get {
                return ResourceManager.GetString("Popup_Message_PasswordRecoveredP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Reset Password&apos;.
        /// </summary>
        public static string Popup_Message_PasswordRecoveredP2 {
            get {
                return ResourceManager.GetString("Popup_Message_PasswordRecoveredP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  section.
        /// </summary>
        public static string Popup_Message_PasswordRecoveredP3 {
            get {
                return ResourceManager.GetString("Popup_Message_PasswordRecoveredP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient name have been updated..
        /// </summary>
        public static string Popup_Message_PatientNameUpdated {
            get {
                return ResourceManager.GetString("Popup_Message_PatientNameUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to recover your password?.
        /// </summary>
        public static string Popup_Message_RecoverPassword {
            get {
                return ResourceManager.GetString("Popup_Message_RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this new analyzer.
        /// </summary>
        public static string Popup_Message_RemoveAnalyzer {
            get {
                return ResourceManager.GetString("Popup_Message_RemoveAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report setting successfully updated..
        /// </summary>
        public static string Popup_Message_ReportSettingUpdated {
            get {
                return ResourceManager.GetString("Popup_Message_ReportSettingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the password?.
        /// </summary>
        public static string Popup_Message_ResetPassword {
            get {
                return ResourceManager.GetString("Popup_Message_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve updated the PMS/LIS/HIS settings. Please Login again to apply changes..
        /// </summary>
        public static string Popup_Message_SavePMSLISHIS {
            get {
                return ResourceManager.GetString("Popup_Message_SavePMSLISHIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save this setting.
        /// </summary>
        public static string Popup_Message_SaveSettings {
            get {
                return ResourceManager.GetString("Popup_Message_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select additional test result to include in report..
        /// </summary>
        public static string Popup_Message_SelectAdditionalTestResult {
            get {
                return ResourceManager.GetString("Popup_Message_SelectAdditionalTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select device to send the request to..
        /// </summary>
        public static string Popup_Message_SelectDevice {
            get {
                return ResourceManager.GetString("Popup_Message_SelectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the parameters that you would like to download..
        /// </summary>
        public static string Popup_Message_SelectParameterDownload {
            get {
                return ResourceManager.GetString("Popup_Message_SelectParameterDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the parameters that you would like to print..
        /// </summary>
        public static string Popup_Message_SelectParameterPrint {
            get {
                return ResourceManager.GetString("Popup_Message_SelectParameterPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request have been sent to the analyzer.
        /// </summary>
        public static string Popup_Message_SentToAnalyzer {
            get {
                return ResourceManager.GetString("Popup_Message_SentToAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is at.
        /// </summary>
        public static string Popup_Message_TheFileIsAt {
            get {
                return ResourceManager.GetString("Popup_Message_TheFileIsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update this new analyzer.
        /// </summary>
        public static string Popup_Message_UpdateAnalyzer {
            get {
                return ResourceManager.GetString("Popup_Message_UpdateAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input patient name..
        /// </summary>
        public static string Popup_Message_UpdatePatientName {
            get {
                return ResourceManager.GetString("Popup_Message_UpdatePatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to update this user profile?.
        /// </summary>
        public static string Popup_Message_UpdateUser {
            get {
                return ResourceManager.GetString("Popup_Message_UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Unique ID..
        /// </summary>
        public static string Popup_Message_WrongID {
            get {
                return ResourceManager.GetString("Popup_Message_WrongID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic Address.
        /// </summary>
        public static string Report_Label_ClinicAddress {
            get {
                return ResourceManager.GetString("Report_Label_ClinicAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic Name.
        /// </summary>
        public static string Report_Label_ClinicName {
            get {
                return ResourceManager.GetString("Report_Label_ClinicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string Report_Label_DateTime {
            get {
                return ResourceManager.GetString("Report_Label_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Report_Label_High {
            get {
                return ResourceManager.GetString("Report_Label_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Report_Label_Low {
            get {
                return ResourceManager.GetString("Report_Label_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size is 2MB.
        /// </summary>
        public static string Report_Label_MaxSize {
            get {
                return ResourceManager.GetString("Report_Label_MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Report_Label_Parameter {
            get {
                return ResourceManager.GetString("Report_Label_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered By.
        /// </summary>
        public static string Report_Label_PoweredBy {
            get {
                return ResourceManager.GetString("Report_Label_PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed By.
        /// </summary>
        public static string Report_Label_PrintedBy {
            get {
                return ResourceManager.GetString("Report_Label_PrintedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed On.
        /// </summary>
        public static string Report_Label_PrintedOn {
            get {
                return ResourceManager.GetString("Report_Label_PrintedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Report_Label_Reference {
            get {
                return ResourceManager.GetString("Report_Label_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report_Label_Report {
            get {
                return ResourceManager.GetString("Report_Label_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers for Report.
        /// </summary>
        public static string Report_Label_ReportHeaders {
            get {
                return ResourceManager.GetString("Report_Label_ReportHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Sample.
        /// </summary>
        public static string Report_Label_ReportSample {
            get {
                return ResourceManager.GetString("Report_Label_ReportSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Title.
        /// </summary>
        public static string Report_Label_ReportTitle {
            get {
                return ResourceManager.GetString("Report_Label_ReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Status.
        /// </summary>
        public static string Report_Label_ResultStatus {
            get {
                return ResourceManager.GetString("Report_Label_ResultStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Value.
        /// </summary>
        public static string Report_Label_ResultValue {
            get {
                return ResourceManager.GetString("Report_Label_ResultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Report_Label_Test {
            get {
                return ResourceManager.GetString("Report_Label_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Logo.
        /// </summary>
        public static string Report_Label_UploadLogo {
            get {
                return ResourceManager.GetString("Report_Label_UploadLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword_Title_PageTitle {
            get {
                return ResourceManager.GetString("ResetPassword_Title_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result (Ascending).
        /// </summary>
        public static string Results_Label_Ascending {
            get {
                return ResourceManager.GetString("Results_Label_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result (Descending).
        /// </summary>
        public static string Results_Label_Descending {
            get {
                return ResourceManager.GetString("Results_Label_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Serial No..
        /// </summary>
        public static string Results_Label_DeviceSerialNo {
            get {
                return ResourceManager.GetString("Results_Label_DeviceSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string Results_Label_Doctor {
            get {
                return ResourceManager.GetString("Results_Label_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Results_Label_Download {
            get {
                return ResourceManager.GetString("Results_Label_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earliest.
        /// </summary>
        public static string Results_Label_Earliest {
            get {
                return ResourceManager.GetString("Results_Label_Earliest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Patient Name.
        /// </summary>
        public static string Results_Label_EditPatientName {
            get {
                return ResourceManager.GetString("Results_Label_EditPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string Results_Label_Latest {
            get {
                return ResourceManager.GetString("Results_Label_Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        public static string Results_Label_Lot {
            get {
                return ResourceManager.GetString("Results_Label_Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Results_Label_No {
            get {
                return ResourceManager.GetString("Results_Label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator ID.
        /// </summary>
        public static string Results_Label_OperatorID {
            get {
                return ResourceManager.GetString("Results_Label_OperatorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        public static string Results_Label_PatientID {
            get {
                return ResourceManager.GetString("Results_Label_PatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string Results_Label_PatientName {
            get {
                return ResourceManager.GetString("Results_Label_PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Results_Label_Print {
            get {
                return ResourceManager.GetString("Results_Label_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedural Control.
        /// </summary>
        public static string Results_Label_ProceduralCont {
            get {
                return ResourceManager.GetString("Results_Label_ProceduralCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Results_Label_Result {
            get {
                return ResourceManager.GetString("Results_Label_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search from keyword.
        /// </summary>
        public static string Results_Label_Searchbar {
            get {
                return ResourceManager.GetString("Results_Label_Searchbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to PMS.
        /// </summary>
        public static string Results_Label_SendToPMS {
            get {
                return ResourceManager.GetString("Results_Label_SendToPMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By :.
        /// </summary>
        public static string Results_Label_SortBy {
            get {
                return ResourceManager.GetString("Results_Label_SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Result Type.
        /// </summary>
        public static string Results_Label_TestResultType {
            get {
                return ResourceManager.GetString("Results_Label_TestResultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Results_Label_Time {
            get {
                return ResourceManager.GetString("Results_Label_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Results_Label_Units {
            get {
                return ResourceManager.GetString("Results_Label_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Filter.
        /// </summary>
        public static string Results_Label_UpdateFilter {
            get {
                return ResourceManager.GetString("Results_Label_UpdateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until.
        /// </summary>
        public static string Results_Label_Valid {
            get {
                return ResourceManager.GetString("Results_Label_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Results_Label_View {
            get {
                return ResourceManager.GetString("Results_Label_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Result Listing completed..
        /// </summary>
        public static string Results_Message_DownloadComplete {
            get {
                return ResourceManager.GetString("Results_Message_DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result download completed..
        /// </summary>
        public static string Results_Message_TestResultDownloadCompleted {
            get {
                return ResourceManager.GetString("Results_Message_TestResultDownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results_Title_PageTitle {
            get {
                return ResourceManager.GetString("Results_Title_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal.
        /// </summary>
        public static string Schedule_Label_Abnormal {
            get {
                return ResourceManager.GetString("Schedule_Label_Abnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Schedule.
        /// </summary>
        public static string Schedule_Label_CancelSchedule {
            get {
                return ResourceManager.GetString("Schedule_Label_CancelSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Patients.
        /// </summary>
        public static string Schedule_Label_NewPatients {
            get {
                return ResourceManager.GetString("Schedule_Label_NewPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Schedule_Label_Normal {
            get {
                return ResourceManager.GetString("Schedule_Label_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Scheduled test available..
        /// </summary>
        public static string Schedule_Label_NoScheduleTestAvailable {
            get {
                return ResourceManager.GetString("Schedule_Label_NoScheduleTestAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No test results available..
        /// </summary>
        public static string Schedule_Label_NoTestResultAvailable {
            get {
                return ResourceManager.GetString("Schedule_Label_NoTestResultAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID:.
        /// </summary>
        public static string Schedule_Label_PatientID {
            get {
                return ResourceManager.GetString("Schedule_Label_PatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Schedule_Label_Patients {
            get {
                return ResourceManager.GetString("Schedule_Label_Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Test Results.
        /// </summary>
        public static string Schedule_Label_RecentTestResults {
            get {
                return ResourceManager.GetString("Schedule_Label_RecentTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to analyzer.
        /// </summary>
        public static string Schedule_Label_SendToAnalyzer {
            get {
                return ResourceManager.GetString("Schedule_Label_SendToAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests Done.
        /// </summary>
        public static string Schedule_Label_TestsDone {
            get {
                return ResourceManager.GetString("Schedule_Label_TestsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique ID:.
        /// </summary>
        public static string Schedule_Label_UniqueID {
            get {
                return ResourceManager.GetString("Schedule_Label_UniqueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Test.
        /// </summary>
        public static string Schedule_Label_UpcomingTest {
            get {
                return ResourceManager.GetString("Schedule_Label_UpcomingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Report.
        /// </summary>
        public static string Schedule_Label_ViewReport {
            get {
                return ResourceManager.GetString("Schedule_Label_ViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Schedule in PMS.
        /// </summary>
        public static string Schedule_Label_ViewSchedulePMS {
            get {
                return ResourceManager.GetString("Schedule_Label_ViewSchedulePMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule_Title_PageTitle {
            get {
                return ResourceManager.GetString("Schedule_Title_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please key in correct date format..
        /// </summary>
        public static string Setting_ErrorMessage_DateFormat {
            get {
                return ResourceManager.GetString("Setting_ErrorMessage_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must include “@” symbol..
        /// </summary>
        public static string Setting_ErrorMessage_EmailFormat {
            get {
                return ResourceManager.GetString("Setting_ErrorMessage_EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must contain at least 5 characters..
        /// </summary>
        public static string Setting_ErrorMessage_FiveCharMin {
            get {
                return ResourceManager.GetString("Setting_ErrorMessage_FiveCharMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP address entered.
        /// </summary>
        public static string Setting_ErrorMessage_InvalidIP {
            get {
                return ResourceManager.GetString("Setting_ErrorMessage_InvalidIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a mandatory field..
        /// </summary>
        public static string Setting_ErrorMessage_MandatoryField {
            get {
                return ResourceManager.GetString("Setting_ErrorMessage_MandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must contain at least 2 characters..
        /// </summary>
        public static string Setting_ErrorMessage_TwoCharMin {
            get {
                return ResourceManager.GetString("Setting_ErrorMessage_TwoCharMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Setting_Label_Country {
            get {
                return ResourceManager.GetString("Setting_Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string Setting_Label_CreateUser {
            get {
                return ResourceManager.GetString("Setting_Label_CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string Setting_Label_DateOfBirth {
            get {
                return ResourceManager.GetString("Setting_Label_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Setting_Label_Device {
            get {
                return ResourceManager.GetString("Setting_Label_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type.
        /// </summary>
        public static string Setting_Label_DeviceType {
            get {
                return ResourceManager.GetString("Setting_Label_DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Setting_Label_Email {
            get {
                return ResourceManager.GetString("Setting_Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Setting_Label_FullName {
            get {
                return ResourceManager.GetString("Setting_Label_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Setting_Label_Gender {
            get {
                return ResourceManager.GetString("Setting_Label_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Setting_Label_Language {
            get {
                return ResourceManager.GetString("Setting_Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language &amp; Country.
        /// </summary>
        public static string Setting_Label_LanguageCountry {
            get {
                return ResourceManager.GetString("Setting_Label_LanguageCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ID.
        /// </summary>
        public static string Setting_Label_LoginID {
            get {
                return ResourceManager.GetString("Setting_Label_LoginID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor&apos;s Registration No..
        /// </summary>
        public static string Setting_Label_RegistrationNo {
            get {
                return ResourceManager.GetString("Setting_Label_RegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string Setting_Label_Role {
            get {
                return ResourceManager.GetString("Setting_Label_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a country.
        /// </summary>
        public static string Setting_Label_SelectCountry {
            get {
                return ResourceManager.GetString("Setting_Label_SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a language.
        /// </summary>
        public static string Setting_Label_SelectLanguage {
            get {
                return ResourceManager.GetString("Setting_Label_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID.
        /// </summary>
        public static string Setting_Label_StaffID {
            get {
                return ResourceManager.GetString("Setting_Label_StaffID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name.
        /// </summary>
        public static string Setting_Label_StaffName {
            get {
                return ResourceManager.GetString("Setting_Label_StaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Setting_Label_Status {
            get {
                return ResourceManager.GetString("Setting_Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Setting_Label_Title {
            get {
                return ResourceManager.GetString("Setting_Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Setting_Label_User {
            get {
                return ResourceManager.GetString("Setting_Label_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to User Listing.
        /// </summary>
        public static string Setting_Label_UserBackButton {
            get {
                return ResourceManager.GetString("Setting_Label_UserBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user existed.
        /// </summary>
        public static string Setting_Message_NoUserData {
            get {
                return ResourceManager.GetString("Setting_Message_NoUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting_Title_PageTitle {
            get {
                return ResourceManager.GetString("Setting_Title_PageTitle", resourceCulture);
            }
        }
    }
}
