INSERT INTO `txn_scheduledtests` (`ID`, `ScheduledTestType`, `ScheduledDateTime`, `ScheduledBy`, `PatientID`, `InchargePerson`, `ScheduleTestStatus`, `CreatedDate`, `CreatedBy`, `UpdatedDate`, `UpdatedBy`) VALUES (1, 'F TBLAM FIA', '2024-02-02 22:25:00', 'Abu', 'Patient ANC', 'Doctor C', 0, '2024-05-09 11:53:49', 'ADMIN', NULL, NULL);
INSERT INTO `txn_scheduledtests` (`ID`, `ScheduledTestType`, `ScheduledDateTime`, `ScheduledBy`, `PatientID`, `InchargePerson`, `ScheduleTestStatus`, `CreatedDate`, `CreatedBy`, `UpdatedDate`, `UpdatedBy`) VALUES (2, 'F TBLAM FIA', '2024-06-09 12:00:00', 'Abu', 'Patient E', 'Doctor C', 0, '2024-05-09 11:54:40', 'ADMIN', NULL, NULL);
INSERT INTO `txn_scheduledtests` (`ID`, `ScheduledTestType`, `ScheduledDateTime`, `ScheduledBy`, `PatientID`, `InchargePerson`, `ScheduleTestStatus`, `CreatedDate`, `CreatedBy`, `UpdatedDate`, `UpdatedBy`) VALUES (3, 'F TBLAM FIA', '2024-06-09 14:30:00', 'Alice', 'Patient 99', 'Doctor C2', 0, '2024-05-09 11:55:05', 'ADMIN', NULL, NULL);
INSERT INTO `txn_scheduledtests` (`ID`, `ScheduledTestType`, `ScheduledDateTime`, `ScheduledBy`, `PatientID`, `InchargePerson`, `ScheduleTestStatus`, `CreatedDate`, `CreatedBy`, `UpdatedDate`, `UpdatedBy`) VALUES (4, 'F TBLAM FIA', '2023-06-09 15:00:00', 'Alice', 'Patient 919', 'Doctor C2', 0, '2024-05-09 11:55:23', 'ADMIN', NULL, NULL);
INSERT INTO `txn_scheduledtests` (`ID`, `ScheduledTestType`, `ScheduledDateTime`, `ScheduledBy`, `PatientID`, `InchargePerson`, `ScheduleTestStatus`, `CreatedDate`, `CreatedBy`, `UpdatedDate`, `UpdatedBy`) VALUES (5, 'F TBLAM FIA', '2023-06-09 15:20:00', 'AhLeong', 'Patient 819', 'Doctor F', 0, '2024-05-09 11:55:56', 'ADMIN', NULL, NULL);
INSERT INTO `txn_scheduledtests` (`ID`, `ScheduledTestType`, `ScheduledDateTime`, `ScheduledBy`, `PatientID`, `InchargePerson`, `ScheduleTestStatus`, `CreatedDate`, `CreatedBy`, `UpdatedDate`, `UpdatedBy`) VALUES (6, 'F TBLAM FIA', '2023-06-09 16:30:00', 'AhLeong', 'Patient YY', 'Doctor F', 0, '2024-05-09 11:56:23', 'ADMIN', NULL, NULL);
INSERT INTO `txn_scheduledtests` (`ID`, `ScheduledTestType`, `ScheduledDateTime`, `ScheduledBy`, `PatientID`, `InchargePerson`, `ScheduleTestStatus`, `CreatedDate`, `CreatedBy`, `UpdatedDate`, `UpdatedBy`) VALUES (7, 'F TBLAM FIA', '2024-06-09 17:30:00', 'Ah T', 'Patient EE', 'Doctor F', 0, '2024-05-09 11:56:39', 'ADMIN', NULL, NULL);

INSERT INTO `txn_testresults` (`ID`, `TestResultDateTime`, `TestResultType`, `OperatorID`, `PatientID`, `InchargePerson`, `ObservationStatus`, `TestResultStatus`, `TestResultValue`, `TestResultRules`, `CreatedDate`, `CreatedBy`, `UpdatedDate`, `UpdatedBy`) VALUES (1, '2024-05-11 13:00:00', 'F TBLAM FIA', 'guest1', 'Patient Z', 'Doctor Z1', '', 'Negative', 0.5700, 'Cut Off Index', '2024-05-10 11:34:03', 'ADMIN', NULL, NULL);
INSERT INTO `txn_testresults` (`ID`, `TestResultDateTime`, `TestResultType`, `OperatorID`, `PatientID`, `InchargePerson`, `ObservationStatus`, `TestResultStatus`, `TestResultValue`, `TestResultRules`, `CreatedDate`, `CreatedBy`, `UpdatedDate`, `UpdatedBy`) VALUES (2, '2024-05-01 20:00:00', 'F TBLAM FIA', 'guest1', 'Patient D', 'Doctor D1', '', 'Positive', 1.1200, 'Cut Off Index', '2024-05-10 11:34:49', 'ADMIN', NULL, NULL);
INSERT INTO `txn_testresults` (`ID`, `TestResultDateTime`, `TestResultType`, `OperatorID`, `PatientID`, `InchargePerson`, `ObservationStatus`, `TestResultStatus`, `TestResultValue`, `TestResultRules`, `CreatedDate`, `CreatedBy`, `UpdatedDate`, `UpdatedBy`) VALUES (3, '2024-05-01 20:00:00', 'F TBLAM FIA', 'guest1', 'Patient 99', 'Doctor Ali', '', 'Negative', 0.1200, 'Cut Off Index', '2024-05-10 11:35:11', 'ADMIN', NULL, NULL);
INSERT INTO `txn_testresults` (`ID`, `TestResultDateTime`, `TestResultType`, `OperatorID`, `PatientID`, `InchargePerson`, `ObservationStatus`, `TestResultStatus`, `TestResultValue`, `TestResultRules`, `CreatedDate`, `CreatedBy`, `UpdatedDate`, `UpdatedBy`) VALUES (4, '2024-05-10 20:00:00', 'F TBLAM FIA', 'guest1', 'Patient 8199', 'Doctor John', '', 'Negative', 0.5500, 'Cut Off Index', '2024-05-10 11:35:34', 'ADMIN', NULL, NULL);
INSERT INTO `txn_testresults` (`ID`, `TestResultDateTime`, `TestResultType`, `OperatorID`, `PatientID`, `InchargePerson`, `ObservationStatus`, `TestResultStatus`, `TestResultValue`, `TestResultRules`, `CreatedDate`, `CreatedBy`, `UpdatedDate`, `UpdatedBy`) VALUES (5, '2024-05-09 15:00:00', 'F TBLAM FIA', 'guest1', 'Patient 23', 'Doctor 2John', '', 'Negative', 0.3300, 'Cut Off Index', '2024-05-10 11:35:59', 'ADMIN', NULL, NULL);
INSERT INTO `txn_testresults` (`ID`, `TestResultDateTime`, `TestResultType`, `OperatorID`, `PatientID`, `InchargePerson`, `ObservationStatus`, `TestResultStatus`, `TestResultValue`, `TestResultRules`, `CreatedDate`, `CreatedBy`, `UpdatedDate`, `UpdatedBy`) VALUES (6, '2024-05-09 14:00:00', 'F TBLAM FIA', 'guest1', 'Patient 1', 'Doctor 1', '', 'Positive', 1.3300, 'Cut Off Index', '2024-05-10 11:36:22', 'ADMIN', NULL, NULL);
