CREATE TABLE `system_processinglog` (
	`ID` BIGINT NOT NULL AUTO_INCREMENT,
	`ProcessingTaskName` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`ProcessingStartDate` DATETIME NULL DEFAULT NULL,
	`ProcessingEndDate` DATETIME NULL DEFAULT NULL,
	`CreatedDate` DATETIME NULL DEFAULT NULL,
	`CreatedBy` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
